spring:
  application:
    name: assignment2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/subscriptions
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver